public class RolePremission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_premission.user_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_premission.group_id
     *
     * @mbggenerated
     */
    private Integer premissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_premission.user_id
     *
     * @return the value of role_premission.user_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public Integer getPremissionId() {
        return premissionId;
    }

    public void setPremissionId(Integer premissionId) {
        this.premissionId = premissionId;
    }
}