

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PremissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premissions
     *
     * @mbggenerated
     */
    int countByExample(PremissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premissions
     *
     * @mbggenerated
     */
    int deleteByExample(PremissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premissions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premissions
     *
     * @mbggenerated
     */
    int insert(Premissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premissions
     *
     * @mbggenerated
     */
    int insertSelective(Premissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premissions
     *
     * @mbggenerated
     */
    List<Premissions> selectByExample(PremissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premissions
     *
     * @mbggenerated
     */
    Premissions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premissions
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Premissions record, @Param("example") PremissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premissions
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Premissions record, @Param("example") PremissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Premissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Premissions record);
    List<Premissions> getAllPremissions();
}